# Generated by Django 4.2 on 2023-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="feed_link",
            field=models.URLField(unique=True),
        ),
    ]
