# Generated by Django 4.2.1 on 2023-06-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0010_alter_podcast_site_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
