# Generated by Django 4.2.1 on 2023-06-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0011_alter_episode_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
