# Generated by Django 4.2.1 on 2023-06-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0012_alter_podcast_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
